import {
  APP_NAME,
  GENNY_HOST,
  GENNY_INITURL,
  GENNY_BRIDGE_PORT,
  GENNY_BRIDGE_VERTEX,
  GENNY_BRIDGE_SERVICE,
  GENNY_BRIDGE_EVENTS,
  GOOGLE_MAPS_APIKEY,
  GOOGLE_MAPS_APIURL,
  UPPY_URL,
  KEYCLOAK_REDIRECTURI,
} from 'react-native-dotenv';

export default {
  APP_NAME,
  GENNY_HOST,
  GENNY_INITURL,
  GENNY_BRIDGE_PORT,
  GENNY_BRIDGE_VERTEX,
  GENNY_BRIDGE_SERVICE,
  GENNY_BRIDGE_EVENTS,
  GOOGLE_MAPS_APIKEY,
  GOOGLE_MAPS_APIURL,
  UPPY_URL,
  KEYCLOAK_REDIRECTURI,
};
