export const KEYCLOAK_CONFIG_FETCH_REQUEST = 'KEYCLOAK_CONFIG_FETCH_REQUEST';
export const KEYCLOAK_CONFIG_FETCH_SUCCESS = 'KEYCLOAK_CONFIG_FETCH_SUCCESS';
export const KEYCLOAK_CONFIG_FETCH_FAILURE = 'KEYCLOAK_CONFIG_FETCH_FAILURE';
